application: myapp
version: 1
runtime: go
api_version: go1
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: ./client/src/css
- url: /img
  static_dir: ./client/src/img
- url: /js
  static_dir: ./client/src/js
- url: /lib
  static_dir: ./client/lib
- url: /partials
  static_dir: ./client/src/partials
- url: /.*
  script: _go_app